In [1]:
!echo hi

hi


In [2]:
!pip install tensorflow

  Using cached protobuf-4.25.4-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.0
    Uninstalling protobuf-3.20.0:
      Successfully uninstalled protobuf-3.20.0

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [3]:
!pip install protobuf==3.20.2

  Using cached protobuf-3.20.2-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.4
    Uninstalling protobuf-4.25.4:
      Successfully uninstalled protobuf-4.25.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.20.2 which is incompatible.

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [4]:
!pip uninstall protobuf -y

Found existing installation: protobuf 3.20.2
Uninstalling protobuf-3.20.2:
  Successfully uninstalled protobuf-3.20.2


In [5]:
!python -m pip install paddlepaddle

  Using cached protobuf-5.28.0-cp38-abi3-manylinux2014_x86_64.whl (316 kB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 5.28.0 which is incompatible.

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [6]:
!pip install opencv-python


[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [7]:
!pip install pandas


[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [8]:
from PIL import Image
import cv2
import numpy as np
import pandas as pd
import tensorflow as tf
print('Successfully imported libraries')

2024-09-07 14:00:27.320021: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-07 14:00:27.329383: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-07 14:00:27.340388: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-07 14:00:27.343671: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-07 14:00:27.352572: I tensorflow/core/platform/cpu_feature_guar

Successfully imported libraries


In [9]:
!pip install pdf2image


[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [10]:
TEST_PDF_PATH='test_pdfs/ACHHAM-DISTRICT-RATES-2081-82.pdf'

In [11]:
from pdf2image import convert_from_path

In [12]:
images = convert_from_path(TEST_PDF_PATH)

In [13]:
!mkdir -p pages

In [14]:
for i in range(len(images)):
  images[i].save('pages/page'+str(i)+'.jpg', 'JPEG')

# Layout

## Installation

In [15]:
!pip install "paddleocr>=2.0.1"
!pip install protobuf==3.20.0
# !git clone --depth 1 https://github.com/PaddlePaddle/PaddleOCR.git


[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
  Using cached protobuf-3.20.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.28.0
    Uninstalling protobuf-5.28.0:
      Successfully uninstalled protobuf-5.28.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.20.0 which is incompatible.
paddlepaddle 2.6.1 requires protobuf>=3.20.2; platform_system != "Windows", but you have protobuf 3.20.0 which is incompatible.

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [16]:
#I download it directly from the site
# !curl -O https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
!pip install layoutparser-0.0.0-py3-none-any.whl
#!pip install "layoutparser[paddledetection]"
# pip install -U layoutparser-0.0.0-py3-none-any.whl

Processing ./layoutparser-0.0.0-py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/amrit/milan/Project/layoutparser-0.0.0-py3-none-any.whl'


[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


## Table Extraction

In [35]:
import cv2
import layoutparser as lp
TEST_IMAGE_PATH="./pages/page10.jpg"
image = cv2.imread(TEST_IMAGE_PATH)

image = image[..., ::-1]

model = lp.PaddleDetectionLayoutModel(config_path="lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config",
                                label_map={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"},
                                enforce_cpu=False,
                                threshold=0.2,
                               enable_mkldnn=True
                                )#math kernel library
# detect
layout = model.detect(image)
print('detected tables in image')


E0907 14:04:27.936393 228761 analysis_config.cc:125] Please use PaddlePaddle with GPU version.


detected tables in image


In [36]:
layout

Layout(_blocks=[TextBlock(block=Rectangle(x_1=180.66497802734375, y_1=0.0, x_2=1590.421630859375, y_2=2340.0), text=None, id=None, type=Figure, parent=None, next=None, score=0.8930692076683044), TextBlock(block=Rectangle(x_1=179.16558837890625, y_1=237.50146484375, x_2=1404.364990234375, y_2=321.7293701171875), text=None, id=None, type=Text, parent=None, next=None, score=0.8648343086242676), TextBlock(block=Rectangle(x_1=457.373291015625, y_1=340.8172912597656, x_2=1092.197998046875, y_2=385.7121276855469), text=None, id=None, type=Text, parent=None, next=None, score=0.7268775105476379), TextBlock(block=Rectangle(x_1=181.40924072265625, y_1=395.725341796875, x_2=1437.449462890625, y_2=912.3358154296875), text=None, id=None, type=Table, parent=None, next=None, score=0.3854312300682068), TextBlock(block=Rectangle(x_1=467.2867431640625, y_1=4.332679748535156, x_2=1115.90625, y_2=206.35946655273438), text=None, id=None, type=Figure, parent=None, next=None, score=0.23805686831474304), TextB

In [37]:
[l.type for l in layout]

['Figure', 'Text', 'Text', 'Table', 'Figure', 'Title', 'Text']

In [38]:
x_1=0
y_1=0
x_2=0
y_2=0

for l in layout:
  #print(l)
  if l.type == 'Table':
    x_1 = int(l.block.x_1)
    y_1 = int(l.block.y_1)
    x_2 = int(l.block.x_2)
    y_2 = int(l.block.y_2)

    break

In [39]:
print(x_1,y_1,x_2,y_2)

181 395 1437 912


In [40]:
im = cv2.imread(TEST_IMAGE_PATH)

In [41]:
cv2.imwrite('ext_im.jpg', im[y_1:y_2,x_1:x_2])

True

# Text Detection and Recognition

In [42]:
from paddleocr import PaddleOCR, draw_ocr

In [43]:
ocr = PaddleOCR(lang='hi')
image_path = 'ext_im.jpg'
image_cv = cv2.imread(image_path)
image_height = image_cv.shape[0]
image_width = image_cv.shape[1]
output = ocr.ocr(image_path)[0]


[2024/09/07 14:04:46] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, use_mlu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/home/amrit/.paddleocr/whl/det/ml/Multilingual_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/home/amrit/.paddleocr/whl/rec/devanagari/devanagari_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_

In [44]:
print(output)

[[[[536.0, 11.0], [611.0, 11.0], [611.0, 44.0], [536.0, 44.0]], ('घरको', 0.997969388961792)], [[[620.0, 11.0], [705.0, 11.0], [705.0, 44.0], [620.0, 44.0]], ('िकिसम', 0.9267207384109497)], [[[92.0, 35.0], [135.0, 35.0], [135.0, 70.0], [92.0, 70.0]], ('सन', 0.6993892788887024)], [[[1095.0, 39.0], [1197.0, 48.0], [1194.0, 87.0], [1092.0, 79.0]], ('कैिफयत', 0.9930494427680969)], [[[309.0, 70.0], [338.0, 70.0], [338.0, 106.0], [309.0, 106.0]], ('A', 0.9994242191314697)], [[[508.0, 73.0], [534.0, 73.0], [534.0, 109.0], [508.0, 109.0]], ('८', 0.9495581984519958)], [[[708.0, 75.0], [737.0, 75.0], [737.0, 109.0], [708.0, 109.0]], ('८', 0.8140665292739868)], [[[98.0, 151.0], [126.0, 151.0], [126.0, 186.0], [98.0, 186.0]], ('क', 0.9863112568855286)], [[[294.0, 151.0], [339.0, 151.0], [339.0, 193.0], [294.0, 193.0]], ('२६', 0.7673514485359192)], [[[492.0, 156.0], [534.0, 156.0], [534.0, 193.0], [492.0, 193.0]], ('९९', 0.7286728620529175)], [[[692.0, 159.0], [738.0, 159.0], [738.0, 193.0], [692.0,

In [45]:
boxes = [line[0] for line in output]
texts = [line[1][0] for line in output]
probabilities = [line[1][1] for line in output]

In [46]:
image_boxes = image_cv.copy()


In [47]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes, (int(box[0][0]),int(box[0][1])), (int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes, text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [48]:
cv2.imwrite('detections.jpg', image_boxes)

True

# Reconstruction

## Get Horizontal and Vertical Lines

In [49]:
im = image_cv.copy()




In [50]:
horiz_boxes = []
vert_boxes = []

for box in boxes:
  x_h, x_v = 0,int(box[0][0])
  y_h, y_v = int(box[0][1]),0
  width_h,width_v = image_width, int(box[2][0]-box[0][0])
  height_h,height_v = int(box[2][1]-box[0][1]),image_height

  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h), (x_h+width_h,y_h+height_h),(0,0,255),1)
  cv2.rectangle(im,(x_v,y_v), (x_v+width_v,y_v+height_v),(0,255,0),1)


In [51]:
cv2.imwrite('horiz_vert.jpg',im)

True

## Non-Max Suppression

In [52]:
horiz_out = tf.image.non_max_suppression(
    horiz_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

I0000 00:00:1725697188.845040  228761 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-09-07 14:04:48.866657: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2343] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [53]:
horiz_lines = np.sort(np.array(horiz_out))
print(horiz_lines)


[ 0  4  7 12 14 18]


In [54]:
im_nms = image_cv.copy()

In [55]:
for val in horiz_lines:
  cv2.rectangle(im_nms, (int(horiz_boxes[val][0]),int(horiz_boxes[val][1])), (int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)


In [56]:
cv2.imwrite('im_nms.jpg',im_nms)

True

In [57]:
vert_out = tf.image.non_max_suppression(
    vert_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)


In [58]:
print(vert_out)

tf.Tensor([ 4  0  3  7  5  1  6 18], shape=(8,), dtype=int32)


In [59]:
vert_lines = np.sort(np.array(vert_out))
print(vert_lines)

[ 0  1  3  4  5  6  7 18]


In [60]:
for val in vert_lines:
  cv2.rectangle(im_nms, (int(vert_boxes[val][0]),int(vert_boxes[val][1])), (int(vert_boxes[val][2]),int(vert_boxes[val][3])),(255,0,0),1)


In [61]:
cv2.imwrite('im_nms.jpg',im_nms)

True

## Convert to CSV

In [62]:


out_array = [["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(np.array(out_array).shape)
print(out_array)

(6, 8)
[['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '']]


In [63]:

unordered_boxes = []

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[536, 0, 611, 517]
[620, 0, 705, 517]
[1095, 0, 1194, 517]
[309, 0, 338, 517]
[508, 0, 534, 517]
[708, 0, 737, 517]
[98, 0, 126, 517]
[895, 0, 942, 517]


In [64]:
ordered_boxes = np.argsort(unordered_boxes)
print(ordered_boxes)

[6 3 4 0 1 5 7 2]


In [65]:
def intersection(box_1, box_2):
  return [box_2[0], box_1[1],box_2[2], box_1[3]]

In [66]:
def iou(box_1, box_2):

  x_1 = max(box_1[0], box_2[0])
  y_1 = max(box_1[1], box_2[1])
  x_2 = min(box_1[2], box_2[2])
  y_2 = min(box_1[3], box_2[3])

  inter = abs(max((x_2 - x_1, 0)) * max((y_2 - y_1), 0))
  if inter == 0:
      return 0

  box_1_area = abs((box_1[2] - box_1[0]) * (box_1[3] - box_1[1]))
  box_2_area = abs((box_2[2] - box_2[0]) * (box_2[3] - box_2[1]))

  return inter / float(box_1_area + box_2_area - inter)

In [67]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant = intersection(horiz_boxes[horiz_lines[i]], vert_boxes[vert_lines[ordered_boxes[j]]] )

    for b in range(len(boxes)):
      the_box = [boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if(iou(resultant,the_box)>0.1):
        out_array[i][j] = texts[b]

In [68]:
out_array=np.array(out_array)

In [69]:
out_array

array([['सन', '', '', 'घरको', 'िकिसम', '', '', ''],
       ['', 'A', '८', '', '', '८', '', 'कैिफयत'],
       ['क', '२६', '९९', '', '', '१६', '१९', ''],
       ['ख', '(', '', '', '', '', '', ''],
       ['गा', '', '९४', '', '', '', '', ''],
       ['घ', '', 'A?', '', '', '', '९०', '']], dtype='<U6')

In [70]:
pd.DataFrame(out_array).to_csv('sample.csv')

## Merging Cells

In [71]:
current_bank=['']*len(out_array[0,:])
print(current_bank)

['', '', '', '', '', '', '', '']


In [72]:
def empty(arr):
  for i in arr:
    if i=='':
      return True
  return False

In [73]:
cleaned_array=[]

In [74]:
for i in range(len(out_array)):
  if not empty(out_array[i]):
    current_bank=[out_array[i][j] for j in range(len(out_array[i]))]
    cleaned_array.append(current_bank)
    not_empty=True
  else:
    for j in range(len(out_array[i])):
      current_bank[j]+=' '+out_array[i][j]
    print('-->',current_bank)
cleaned_array=np.array(cleaned_array)
print(cleaned_array)

--> [' सन', ' ', ' ', ' घरको', ' िकिसम', ' ', ' ', ' ']
--> [' सन ', '  A', '  ८', ' घरको ', ' िकिसम ', '  ८', '  ', '  कैिफयत']
--> [' सन  क', '  A २६', '  ८ ९९', ' घरको  ', ' िकिसम  ', '  ८ १६', '   १९', '  कैिफयत ']
--> [' सन  क ख', '  A २६ (', '  ८ ९९ ', ' घरको   ', ' िकिसम   ', '  ८ १६ ', '   १९ ', '  कैिफयत  ']
--> [' सन  क ख गा', '  A २६ ( ', '  ८ ९९  ९४', ' घरको    ', ' िकिसम    ', '  ८ १६  ', '   १९  ', '  कैिफयत   ']
--> [' सन  क ख गा घ', '  A २६ (  ', '  ८ ९९  ९४ A?', ' घरको     ', ' िकिसम     ', '  ८ १६   ', '   १९   ९०', '  कैिफयत    ']
[]


In [75]:
pd.DataFrame(cleaned_array).to_csv('cleaned.csv')