In [8]:
!pip install tensorflow

In [9]:
!pip install protobuf<=3.20.2,>=3.1.0

The system cannot find the file specified.


In [10]:
!pip uninstall protobuf

^C


In [14]:
from PIL import Image
import cv2
import numpy as np
import pandas as pd
import tensorflow as tf

ModuleNotFoundError: No module named 'distutils'

In [2]:
!python -m pip install paddlepaddle

# pdf2image

## Installation

In [3]:
!pip install pdf2image


## Conversion

In [7]:
from pdf2image import convert_from_path

In [8]:
images = convert_from_path('C:\\Users\\Milan\\Documents\\Project\\BAJHANG-DISTRICT-RATES-2081-82.pdf')


In [9]:
!mkdir pages

In [10]:
for i in range(len(images)):
  images[i].save('pages/page'+str(i)+'.jpg', 'JPEG')

# Layout

## Installation

In [11]:
!pip install "paddleocr>=2.0.1"
!pip install protobuf==3.20.0
!git clone https://github.com/PaddlePaddle/PaddleOCR.git

  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.2
    Uninstalling protobuf-3.20.2:
      Successfully uninstalled protobuf-3.20.2


Cloning into 'PaddleOCR'...
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2249 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output


In [20]:
#I download it directly from the site
#!curl -O https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
!pip install -U layoutparser-0.0.0-py3-none-any.whl
!pip install paddlepaddle

Processing c:\users\milan\documents\project\youtube\layoutparser-0.0.0-py3-none-any.whl
layoutparser is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.


## Table Extraction

In [22]:
import cv2
import layoutparser as lp
image = cv2.imread("C:\\Users\\Milan\\Documents\\Project\\youtube\\pages\\page6.jpg")

image = image[..., ::-1]

# load model
model = lp.PaddleDetectionLayoutModel(config_path="lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config",
                                threshold=0.5,
                                label_map={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"},
                                enforce_cpu=False,
                                enable_mkldnn=True)#math kernel library
# detect
layout = model.detect(image)

Error: Can not import paddle core while this file exists: c:\Users\Milan\Documents\Project\myvenv\Lib\site-packages\paddle\base\libpaddle.pyd


ImportError: DLL load failed while importing libpaddle: The specified module could not be found.

In [ ]:
layout

Layout(_blocks=[TextBlock(block=Rectangle(x_1=300.35406494140625, y_1=1716.4278564453125, x_2=1401.105712890625, y_2=1876.4561767578125), text=None, id=None, type=Text, parent=None, next=None, score=0.947794497013092), TextBlock(block=Rectangle(x_1=296.242431640625, y_1=1969.3675537109375, x_2=1405.8653564453125, y_2=2034.4422607421875), text=None, id=None, type=Text, parent=None, next=None, score=0.934190034866333), TextBlock(block=Rectangle(x_1=296.2332763671875, y_1=1460.10986328125, x_2=1401.1175537109375, y_2=1553.036865234375), text=None, id=None, type=Text, parent=None, next=None, score=0.924132227897644), TextBlock(block=Rectangle(x_1=294.98626708984375, y_1=444.1419677734375, x_2=1408.130126953125, y_2=567.1005249023438), text=None, id=None, type=Text, parent=None, next=None, score=0.9196642637252808), TextBlock(block=Rectangle(x_1=300.4600830078125, y_1=1669.076171875, x_2=711.9566040039062, y_2=1697.28076171875), text=None, id=None, type=Title, parent=None, next=None, score=

In [ ]:
x_1=0
y_1=0
x_2=0
y_2=0

for l in layout:
  #print(l)
  if l.type == 'Table':
    x_1 = int(l.block.x_1)
    print(l.block.x_1)
    y_1 = int(l.block.y_1)
    x_2 = int(l.block.x_2)
    y_2 = int(l.block.y_2)

    break

297.86298


In [ ]:
print(x_1,y_1,x_2,y_2)

297 220 1409 418


In [ ]:
im = cv2.imread('/content/pages/page13.jpg')

In [ ]:
cv2.imwrite('ext_im.jpg', im[y_1:y_2,x_1:x_2])

True

# Text Detection and Recognition

In [ ]:
from paddleocr import PaddleOCR, draw_ocr

In [ ]:
ocr = PaddleOCR(lang='en')
image_path = '/content/ext_im.jpg'
image_cv = cv2.imread(image_path)
image_height = image_cv.shape[0]
image_width = image_cv.shape[1]
output = ocr.ocr(image_path)[0]

download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar to /root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer/en_PP-OCRv3_det_infer.tar


100%|██████████| 4.00M/4.00M [00:07<00:00, 505kiB/s] 


download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar to /root/.paddleocr/whl/rec/en/en_PP-OCRv3_rec_infer/en_PP-OCRv3_rec_infer.tar


100%|██████████| 9.96M/9.96M [00:14<00:00, 693kiB/s] 


download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar to /root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.tar


100%|██████████| 2.19M/2.19M [00:11<00:00, 190kiB/s]

[2022/11/18 13:00:00] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set

[2022/11/18 13:00:00] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2022/11/18 13:00:01] ppocr DEBUG: dt_boxes num : 42, elapse : 0.12288975715637207
[2022/11/18 13:00:01] ppocr DEBUG: rec_res num  : 42, elapse : 0.12553930282592773


In [ ]:
print(output)

[[[[693.0, 4.0], [755.0, 4.0], [755.0, 36.0], [693.0, 36.0]], ('GPU', 0.9990124106407166)], [[[70.0, 5.0], [148.0, 5.0], [148.0, 36.0], [70.0, 36.0]], ('Model', 0.9997721910476685)], [[[230.0, 5.0], [394.0, 8.0], [394.0, 37.0], [229.0, 35.0]], ('Updates (105)', 0.9652137756347656)], [[[425.0, 5.0], [511.0, 5.0], [511.0, 36.0], [425.0, 36.0]], ('Epochs', 0.9998965263366699)], [[[537.0, 5.0], [612.0, 5.0], [612.0, 36.0], [537.0, 36.0]], ('Hours', 0.9620624780654907)], [[[833.0, 4.0], [958.0, 4.0], [958.0, 33.0], [833.0, 33.0]], ('Train NLL', 0.9994094371795654)], [[[988.0, 6.0], [1104.0, 6.0], [1104.0, 32.0], [988.0, 32.0]], ('Dev.NLL', 0.9872051477432251)], [[[42.0, 47.0], [177.0, 47.0], [177.0, 72.0], [42.0, 72.0]], ('RNNenc-30', 0.9995856881141663)], [[[285.0, 46.0], [341.0, 46.0], [341.0, 74.0], [285.0, 74.0]], ('8.46', 0.9999933242797852)], [[[446.0, 46.0], [489.0, 46.0], [489.0, 74.0], [446.0, 74.0]], ('6.4', 0.9964627623558044)], [[[553.0, 45.0], [599.0, 45.0], [599.0, 74.0], [553

In [ ]:
boxes = [line[0] for line in output]
texts = [line[1][0] for line in output]
probabilities = [line[1][1] for line in output]

In [ ]:
image_boxes = image_cv.copy()


In [ ]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes, (int(box[0][0]),int(box[0][1])), (int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes, text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [ ]:
cv2.imwrite('detections.jpg', image_boxes)

True

# Reconstruction

## Get Horizontal and Vertical Lines

In [ ]:
im = image_cv.copy()

In [ ]:
horiz_boxes = []
vert_boxes = []

for box in boxes:
  x_h, x_v = 0,int(box[0][0])
  y_h, y_v = int(box[0][1]),0
  width_h,width_v = image_width, int(box[2][0]-box[0][0])
  height_h,height_v = int(box[2][1]-box[0][1]),image_height

  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h), (x_h+width_h,y_h+height_h),(0,0,255),1)
  cv2.rectangle(im,(x_v,y_v), (x_v+width_v,y_v+height_v),(0,255,0),1)


In [ ]:
cv2.imwrite('horiz_vert.jpg',im)

True

## Non-Max Suppression

In [ ]:
horiz_out = tf.image.non_max_suppression(
    horiz_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [ ]:
horiz_lines = np.sort(np.array(horiz_out))
print(horiz_lines)

[ 3  8 20 24 34 36]


In [ ]:
im_nms = image_cv.copy()

In [ ]:
for val in horiz_lines:
  cv2.rectangle(im_nms, (int(horiz_boxes[val][0]),int(horiz_boxes[val][1])), (int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)


In [ ]:
cv2.imwrite('im_nms.jpg',im_nms)

True

In [ ]:
vert_out = tf.image.non_max_suppression(
    vert_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [ ]:
print(vert_out)

tf.Tensor([ 8 10 34 12  3  1 39], shape=(7,), dtype=int32)


In [ ]:
vert_lines = np.sort(np.array(vert_out))
print(vert_lines)

[ 1  3  8 10 12 34 39]


In [ ]:
for val in vert_lines:
  cv2.rectangle(im_nms, (int(vert_boxes[val][0]),int(vert_boxes[val][1])), (int(vert_boxes[val][2]),int(vert_boxes[val][3])),(255,0,0),1)


In [ ]:
cv2.imwrite('im_nms.jpg',im_nms)

True

## Convert to CSV

In [ ]:


out_array = [["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(np.array(out_array).shape)
print(out_array)

(6, 7)
[['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', '']]


In [ ]:

unordered_boxes = []

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[70, 0, 148, 198]
[425, 0, 511, 198]
[285, 0, 341, 198]
[553, 0, 599, 198]
[869, 0, 923, 198]
[1018, 0, 1075, 198]
[644, 0, 804, 198]


In [ ]:
ordered_boxes = np.argsort(unordered_boxes)
print(ordered_boxes)

[0 2 1 3 6 4 5]


In [ ]:
def intersection(box_1, box_2):
  return [box_2[0], box_1[1],box_2[2], box_1[3]]

In [ ]:
def iou(box_1, box_2):

  x_1 = max(box_1[0], box_2[0])
  y_1 = max(box_1[1], box_2[1])
  x_2 = min(box_1[2], box_2[2])
  y_2 = min(box_1[3], box_2[3])

  inter = abs(max((x_2 - x_1, 0)) * max((y_2 - y_1), 0))
  if inter == 0:
      return 0

  box_1_area = abs((box_1[2] - box_1[0]) * (box_1[3] - box_1[1]))
  box_2_area = abs((box_2[2] - box_2[0]) * (box_2[3] - box_2[1]))

  return inter / float(box_1_area + box_2_area - inter)

In [ ]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant = intersection(horiz_boxes[horiz_lines[i]], vert_boxes[vert_lines[ordered_boxes[j]]] )

    for b in range(len(boxes)):
      the_box = [boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if(iou(resultant,the_box)>0.1):
        out_array[i][j] = texts[b]

In [ ]:
out_array=np.array(out_array)

In [ ]:
out_array

array([['Model', 'Updates (105)', 'Epochs', 'Hours', 'GPU', 'Train NLL',
        'Dev.NLL'],
       ['RNNenc-30', '8.46', '6.4', '109', 'TITAN BLACK', '28.1', '53.0'],
       ['RNNenc-50', '6.00', '4.5', '108', 'Quadro K-6000', '44.0',
        '43.6'],
       ['RNNsearch-30', '4.71', '3.6', '113', 'TITAN BLACK', '26.7',
        '47.2'],
       ['RNNsearch-50', '2.88', '2.2', '111', 'Quadro K-6000', '40.7',
        '38.1'],
       ['RNNsearch-50*', '6.67', '5.0', '252', 'Quadro K-6000', '36.7',
        '35.2']], dtype='<U13')

In [ ]:
pd.DataFrame(out_array).to_csv('sample.csv')

## Merging Cells

In [ ]:
current_bank=['']*len(out_array[0,:])
print(current_bank)

['', '', '', '', '', '', '']


In [ ]:
def empty(arr):
  for i in arr:
    if i=='':
      return True
  return False

In [ ]:
cleaned_array=[]

In [ ]:
for i in range(len(out_array)):
  if not empty(out_array[i]):
    current_bank=[out_array[i][j] for j in range(len(out_array[i]))]
    cleaned_array.append(current_bank)
    not_empty=True
  else:
    for j in range(len(out_array[i])):
      current_bank[j]+=' '+out_array[i][j]
    print('-->',current_bank)
cleaned_array=np.array(cleaned_array)
print(cleaned_array)

[['Model' 'Updates (105)' 'Epochs' 'Hours' 'GPU' 'Train NLL' 'Dev.NLL']
 ['RNNenc-30' '8.46' '6.4' '109' 'TITAN BLACK' '28.1' '53.0']
 ['RNNenc-50' '6.00' '4.5' '108' 'Quadro K-6000' '44.0' '43.6']
 ['RNNsearch-30' '4.71' '3.6' '113' 'TITAN BLACK' '26.7' '47.2']
 ['RNNsearch-50' '2.88' '2.2' '111' 'Quadro K-6000' '40.7' '38.1']
 ['RNNsearch-50*' '6.67' '5.0' '252' 'Quadro K-6000' '36.7' '35.2']]


In [ ]:
pd.DataFrame(cleaned_array).to_csv('cleaned.csv')

# Convert to OWL Format

# **CSV to Text**

In [ ]:
import  jpype
import  asposecells


jpype.startJVM()
from asposecells.api import Workbook

workbook = Workbook("/content/sample.csv")
workbook.save("Output.docx")
jpype.shutdownJVM()

ModuleNotFoundError: ignored

# Brighten Image (For Anyone dealing with PDFs created from scanned images)

In [24]:
from PIL import Image, ImageEnhance

#read the image
im = Image.open("C:\\Users\\Milan\\Documents\\Project\\youtube\\pages\\page6.jpg")

#image brightness enhancer
enhancer = ImageEnhance.Brightness(im)

factor = 1 #gives original image
im_output = enhancer.enhance(factor)
im_output.save('C:\\Users\\Milan\\Documents\\Project\\youtube\\pages\\page6.jpg')

factor = 1## brightens the image
im_output = enhancer.enhance(factor)
im_output.save('C:\\Users\\Milan\\Documents\\Project\\youtube\\pages\\page6.jpg')
